/* Autogenerated header file. Please do not edit. */

/* Input structure */
static const char *invarNameList[] = {
        "backscatter",
        "temperature",
        "temperature_ingest",
        "temperature_vap",
        NULL
};

#ifndef _INPUT_FIELDS
#define _INPUT_FIELDS

/* Input Offsets */
#define BACKSCATTER 0
#define TEMPERATURE 1
#define TEMPERATURE_INGEST 2
#define TEMPERATURE_VAP 3

#endif /* _INPUT_FIELDS */
