/* Autogenerated header file. Please do not edit. */

/* Output structures */
static const char *outvarNameList_tutorial30s_c1[] = {
        "base_time",
        "alt",
        "lon",
        "lat",
        "backscatter",
        "q__c_temperature",
        "temperature",
        "range_bounds",
        "range",
        "time_bounds",
        "time",
        "time_offset",
        NULL
};
static const char *outvarNameList_tutorial_c1[] = {
        "base_time",
        "alt",
        "lon",
        "lat",
        "source_temperature",
        "temperature",
        "temperature_ingest",
        "temperature_vap",
        "time_bounds",
        "time",
        "time_offset",
        NULL
};

#ifndef _OUTPUT_FIELDS
#define _OUTPUT_FIELDS

/* Output offsets */
#define TUTORIAL30S_C1_BASE_TIME 0
#define TUTORIAL30S_C1_ALT 1
#define TUTORIAL30S_C1_LON 2
#define TUTORIAL30S_C1_LAT 3
#define TUTORIAL30S_C1_BACKSCATTER 4
#define TUTORIAL30S_C1_Q__C_TEMPERATURE 5
#define TUTORIAL30S_C1_TEMPERATURE 6
#define TUTORIAL30S_C1_RANGE_BOUNDS 7
#define TUTORIAL30S_C1_RANGE 8
#define TUTORIAL30S_C1_TIME_BOUNDS 9
#define TUTORIAL30S_C1_TIME 10
#define TUTORIAL30S_C1_TIME_OFFSET 11
#define TUTORIAL_C1_BASE_TIME 0
#define TUTORIAL_C1_ALT 1
#define TUTORIAL_C1_LON 2
#define TUTORIAL_C1_LAT 3
#define TUTORIAL_C1_SOURCE_TEMPERATURE 4
#define TUTORIAL_C1_TEMPERATURE 5
#define TUTORIAL_C1_TEMPERATURE_INGEST 6
#define TUTORIAL_C1_TEMPERATURE_VAP 7
#define TUTORIAL_C1_TIME_BOUNDS 8
#define TUTORIAL_C1_TIME 9
#define TUTORIAL_C1_TIME_OFFSET 10

#endif /* _OUTPUT_FIELDS */
