/* Autogenerated header file. Please do not edit. */

/* Input structure */
static const char *transvarNameList_half_min_grid_ceil[] = {
        "backscatter",
        NULL
};
static const char *transvarNameList_half_min_grid_temp30s[] = {
        "temperature",
        NULL
};
static const char *transvarNameList_metb1_tingest[] = {
        "temperature_ingest",
        NULL
};
static const char *transvarNameList_metb1_tvap[] = {
        "temperature_vap",
        NULL
};


#ifndef _TRANS_FIELDS
#define _TRANS_FIELDS

/* Input Offsets */
#define HALF_MIN_GRID_CEIL_BACKSCATTER 0
#define HALF_MIN_GRID_TEMP30S_TEMPERATURE 0
#define METB1_TINGEST_TEMPERATURE_INGEST 0
#define METB1_TVAP_TEMPERATURE_VAP 0


#endif /* _TRANS_FIELDS */
